import type { Metadata } from "next";
import Link from "next/link";
import ClaudeAI from "./ui/claude";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

type NavLink = { href: string; label: string };
const NAV_LINKS: NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/css_battle_1", label: "CSS Battle 1" },
  { href: "/css_battle_2", label: "CSS Battle 2" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="nav-pill-wrap">
          <nav className="nav-pill" aria-label="Main">
            <ClaudeAI className="nav-pill__icon-svg" aria-hidden="true" />
            {NAV_LINKS.map(({ href, label }) => (
              <Link key={href} className="nav-pill__link" href={href}>
                {label}
              </Link>
            ))}
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
